name: LiteLottery
main: net.myunco.litelottery.LiteLottery
version: 1.4.1
api-version: 1.13
author: myunco
softdepend:
  - Vault
  - PlayerPoints
folia-supported: true
commands:
  LiteLottery:
    aliases: lot
    permission: LiteLottery.admin
    permission-message: '§cYou don''t have permission!'
  Lottery:
    aliases: lt
    permission: LiteLottery.Lottery
    permission-message: '§cYou don''t have permission!'
permissions:
  LiteLottery.admin:
    default: op
  LiteLottery.Lottery:
    default: true
  LiteLottery.bypass:
    default: op